### ISSUE TITLE
Box Api not access.

### ISSUE THREAD

**Issue by SanjayAndroidDev** [zoom/zoom-sdk-android#12]
I register app box console and able to authenticate the application. But get below error from zoom adk.

android.view.WindowLeaked: Activity us.zoom.androidlib.app.ZMFileListActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{1e95a220 V.E..... R......D 0,0-329,230} that was originally added here
                                                                           at android.view.ViewRootImpl.<init>(ViewRootImpl.java:363)
                                                                           at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:271)
                                                                           at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
                                                                           at android.app.Dialog.show(Dialog.java:298)
                                                                           at us.zoom.androidlib.app.ZMFileListBaseAdapter.showWaitingDialog(ZMFileListBaseAdapter.java:354)
                                                                           at com.zipow.videobox.box.BoxFileListAdapter.openDir(BoxFileListAdapter.java:106)
                                                                           at us.zoom.androidlib.app.ZMFileListActivity.open(ZMFileListActivity.java:350)
                                                                           at us.zoom.androidlib.app.ZMFileListActivity.onStarted(ZMFileListActivity.java:545)
                                                                           at com.zipow.videobox.box.BoxFileListAdapter.onAuthSuccess(BoxFileListAdapter.java:247)
                                                                           at com.zipow.videobox.box.Box$1.run(Box.java:217)
                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:135)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by JackyDuu** [comment]
Could you provide your zoom SDK version and simple code snippet for reproducing this issue?

**Comment by carsonzoom** [comment]
Hi! Thanks for using Zoom Android SDK. This issue is being closed since it is not active for a while. If this is still an issue with the latest version of our SDK, please create a new issue and make sure the template is fully filled out. Thanks! :)
