### ISSUE TITLE
APP Crash when start meeting

### ISSUE THREAD

**Issue by SanjayAndroidDev** [zoom/zoom-sdk-android#22]
Hello Everyone,
I just update the library  for support 26 version. But it's crashing. And give me below error

java.lang.NoSuchFieldError: No static field panelAudioShare of type I in class Lus/zoom/videomeetings/R$id; or its superclasses (declaration of 'us.zoom.videomeetings.R$id' appears in /data/app/com.onetoall.meeting11-Kk57HYGO12V7Nbh_u6O5VA==/base.apk)
                                                                            at com.zipow.videobox.ConfActivityNormal.onCreate(ConfActivityNormal.java:496)
                                                                            at android.app.Activity.performCreate(Activity.java:7009)
                                                                            at android.app.Activity.performCreate(Activity.java:7000)
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
                                                                            at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                            at android.os.Looper.loop(Looper.java:164)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6501)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by JackyDuu** [comment]
Try to clean and rebuild your project.

**Comment by SanjayAndroidDev** [comment]
Hi JackyDuu, Thanks for the quick reply. I tried this one. But still getting error
