### ISSUE TITLE
java.lang.UnsatisfiedLinkError has been thrown while initialize Zoom SDK

### ISSUE THREAD

**Issue by kaprat** [zoom/zoom-sdk-android#28]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/PACKAGE_NAME-Fgp-7LZEsAi_oon12WpNUw==/base.apk"],nativeLibraryDirectories=[/data/app/PACKAGE_NAME-Fgp-7LZEsAi_oon12WpNUw==/lib/x86, /system/lib, /system/vendor/lib]]] couldn't find "libzoom_stlport.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at com.zipow.cmmlib.AppContext.<clinit>(AppContext.java:31)
        at com.zipow.cmmlib.AppContext.initialize(AppContext.java:64)
        at us.zoom.sdk.ZoomSDK.initialize(ZoomSDK.java:243)
        at us.zoom.sdk.ZoomSDK.initialize(ZoomSDK.java:202)
        at MYACTIVITY.onCreate(DashboardActivity.java:196)
        at android.app.Activity.performCreate(Activity.java:6975)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

Code i am using while initialize sdk

ZoomSDK sdk = ZoomSDK.getInstance();
        sdk.initialize(this, "api_key, "api_secret, "", new ZoomSDKInitializeListener() {
            @Override
            public void onZoomSDKInitializeResult(int i, int i1) {

            }
        });

build.gradle

apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "PACKAGE_NAME"
        minSdkVersion 15
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        //Zoom SDK
        /*ndk {
            abiFilters "armeabi", "armeabi-v7a", "x86", "mips"
        }*/
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    //Zoom SDK
    splits {
        abi {
            enable true
            reset()
            include 'x86', 'armeabi-v7a'
            universalApk true
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:design:28.0.0'
    implementation 'com.google.firebase:firebase-messaging:17.3.4'//Push Notification
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    testImplementation 'junit:junit:4.12'
    implementation project(':commonlib')
    implementation project(':mobilertc')
}
apply plugin: 'com.google.gms.google-services'

**Comment by nixusUM** [comment]
same crash on Xiomi devices

**Comment by nixusUM** [comment]
> java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/PACKAGE_NAME-Fgp-7LZEsAi_oon12WpNUw==/base.apk"],nativeLibraryDirectories=[/data/app/PACKAGE_NAME-Fgp-7LZEsAi_oon12WpNUw==/lib/x86, /system/lib, /system/vendor/lib]]] couldn't find "libzoom_stlport.so"
> at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
> at java.lang.System.loadLibrary(System.java:1657)
> at com.zipow.cmmlib.AppContext.(AppContext.java:31)
> at com.zipow.cmmlib.AppContext.initialize(AppContext.java:64)
> at us.zoom.sdk.ZoomSDK.initialize(ZoomSDK.java:243)
> at us.zoom.sdk.ZoomSDK.initialize(ZoomSDK.java:202)
> at MYACTIVITY.onCreate(DashboardActivity.java:196)
> at android.app.Activity.performCreate(Activity.java:6975)
> at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
> at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
> at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
> at android.app.ActivityThread.-wrap11(Unknown Source:0)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
> at android.os.Handler.dispatchMessage(Handler.java:105)
> at android.os.Looper.loop(Looper.java:164)
> at android.app.ActivityThread.main(ActivityThread.java:6541)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
> 
> Code i am using while initialize sdk
> 
> ZoomSDK sdk = ZoomSDK.getInstance();
> sdk.initialize(this, "api_key, "api_secret, "", new ZoomSDKInitializeListener() {
> @override
> public void onZoomSDKInitializeResult(int i, int i1) {
> 
> ```
>         }
>     });
> ```
> build.gradle
> 
> apply plugin: 'com.android.application'
> 
> android {
> compileSdkVersion 28
> defaultConfig {
> applicationId "PACKAGE_NAME"
> minSdkVersion 15
> targetSdkVersion 28
> versionCode 1
> versionName "1.0"
> multiDexEnabled true
> testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
> //Zoom SDK
> /_ndk { abiFilters "armeabi", "armeabi-v7a", "x86", "mips" }_/
> }
> buildTypes {
> release {
> minifyEnabled false
> proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
> }
> }
> //Zoom SDK
> splits {
> abi {
> enable true
> reset()
> include 'x86', 'armeabi-v7a'
> universalApk true
> }
> }
> }
> 
> dependencies {
> implementation fileTree(include: ['*.jar'], dir: 'libs')
> implementation 'com.android.support.constraint:constraint-layout:1.1.3'
> implementation 'com.android.support:appcompat-v7:28.0.0'
> implementation 'com.android.support:design:28.0.0'
> implementation 'com.google.firebase:firebase-messaging:17.3.4'//Push Notification
> androidTestImplementation 'com.android.support.test🏃1.0.2'
> androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
> testImplementation 'junit:junit:4.12'
> implementation project(':commonlib')
> implementation project(':mobilertc')
> }
> apply plugin: 'com.google.gms.google-services'

check this link https://stackoverflow.com/questions/27186726/java-lang-unsatisfiedlinkerror-dalvik-system-pathclassloader

**Comment by JackyDuu** [comment]
Zoom SDK only provide libraries for armeabi-v7a,   if you want to integrate zoom SDK, you need config your abifilters as below,
 ndk {
    abiFilters  "armeabi-v7a" 
}

**Comment by kaprat** [comment]
![zoomsdk](https://user-images.githubusercontent.com/29137068/47993829-929b9500-e116-11e8-98c2-a20f918bf445.png)

I have added 
**ndk {
abiFilters "armeabi-v7a"
}**
after that when i run the app i am getting this i am unable to run the app.

**Comment by JackyDuu** [comment]
Please run it on the real Android device. Zoom sdk doesn't support run on x86 emulator devices.
