### ISSUE TITLE
Crash when start meeting

### ISSUE THREAD

**Issue by nixusUM** [zoom/zoom-sdk-android#29]
Fatal Exception: io.reactivex.exceptions.UndeliverableException
java.lang.IllegalAccessError: Illegal class access: 
when start meeting app crashes

**Comment by JackyDuu** [comment]
This seems not Zoom SDK's issue, could you describe the issue detailedly?

**Comment by nixusUM** [comment]
> This seems not Zoom SDK's issue, could you describe the issue detailedly?

Yes, E/AndroidRuntime: FATAL EXCEPTION: main
    Process: app.**, PID: 12094
    io.reactivex.exceptions.UndeliverableException: java.lang.IllegalAccessError: Illegal class access: 'app.**.ActivtyClass' attempting to access 'us.zoom.sdk.StartMeetingParams' (declaration of 'app.**.ActivtyClass' appears in /data/app/app.**/base.apk:classes4.dex)
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:366)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:111)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6823)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
     Caused by: java.lang.IllegalAccessError: Illegal class access: 'app.**.ActivtyClass' attempting to access 'us.zoom.sdk.StartMeetingParams' (declaration of 'app.**.ActivtyClass' appears in /data/app/app.**-1/base.apk:classes4.dex)
        at app.**.ActivtyClass.startMeeting(ActivtyClass.kt:38)
        at app.**.ActivtyClass$startZoomMeeting$3.accept(ActivtyPresenter.kt:79)
        at app.**.ActivtyClass$startZoomMeeting$3.accept(ActivtyPresenter.kt:10)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6823) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

**Comment by JackyDuu** [comment]
StartMeetingParams is not a public class, please check your code, thanks.

**Comment by nixusUM** [comment]
> StartMeetingParams is not a public class, please check your code, thanks.

```
        val meetingService = ZoomSDK.getInstance().meetingService
        val params = StartMeetingParamsWithoutLogin()
        params.userId = zoomUserId
        params.zoomToken = zoomToken.token
        params.userType = MeetingService.USER_TYPE_API_USER
        params.displayName = "Video Call"
        params.zoomAccessToken = zoomToken.zak
        params.meetingNo = meetingId
        meetingService.startMeetingWithParams(activity, params, opts)
```
what wrong here?

**Comment by JackyDuu** [comment]
Try to not call zoom startmeeting interface by Kotlin directly and a java interface to warp this api.

**Comment by nixusUM** [comment]
> Try to not call zoom startmeeting interface by Kotlin directly and a java interface to warp this api.

I'm not clear understanding your answer, do you mean execute this method like this?

val meet = meetingService.startMeetingWithParams(activity, params, opts) - with this call same crash

**Comment by nixusUM** [comment]
> StartMeetingParams is not a public class, please check your code, thanks.

The old method startMeeting, which is now deprecated executes fine without any crashes, what I need to do to resolve this crash?

**Comment by JackyDuu** [comment]
Create a Java class to warp zoom API like below:
`package us.zoom.sdkexample;

import android.content.Context;

import us.zoom.sdk.MeetingService;
import us.zoom.sdk.StartMeetingOptions;
import us.zoom.sdk.StartMeetingParamsWithoutLogin;

public class MeetingInterfaceWarpper {
    public static int startMeeting(MeetingService service, Context context, StartMeetingParamsWithoutLogin params, StartMeetingOptions opts) {
        return service.startMeetingWithParams(context, params, opts);
    }
}`

Then call this interface in your kotlin code:
`      val meetingService = ZoomSDK.getInstance().meetingService
        val params = StartMeetingParamsWithoutLogin()
        params.userId = zoomUserId
        params.zoomToken = zoomToken.token
        params.userType = MeetingService.USER_TYPE_API_USER
        params.displayName = "Video Call"
        params.zoomAccessToken = zoomToken.zak
        params.meetingNo = meetingId
        MeetingInterfaceWarpper .startMeeting(meetingService ,activity, params, opts)`

**Comment by nixusUM** [comment]
> Create a Java class to warp zoom API like below:
> 
> ```
> package us.zoom.sdkexample;
> import android.content.Context;
> 
> import us.zoom.sdk.MeetingService;
> import us.zoom.sdk.StartMeetingOptions;
> import us.zoom.sdk.StartMeetingParamsWithoutLogin;
> 
> public class MeetingInterfaceWarpper {
>     public static int startMeeting(MeetingService service, Context context, StartMeetingParamsWithoutLogin params, StartMeetingOptions opts) {
>         return service.startMeetingWithParams(context, params, opts);
>     }
> }
> ```
> Then call this interface in your kotlin code:
> 
> ```
>  val meetingService = ZoomSDK.getInstance().meetingService
>         val params = StartMeetingParamsWithoutLogin()
>         params.userId = zoomUserId
>         params.zoomToken = zoomToken.token
>         params.userType = MeetingService.USER_TYPE_API_USER
>         params.displayName = "Video Call"
>         params.zoomAccessToken = zoomToken.zak
>         params.meetingNo = meetingId
>         MeetingInterfaceWarpper .startMeeting(meetingService ,activity, params, opts)
> ```

thank you, I will try

**Comment by nixusUM** [comment]
All works, thank you
