### ISSUE TITLE
Installation failed with message INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113.

### ISSUE THREAD

**Issue by kaprat** [zoom/zoom-sdk-android#30]
I am getting this issue while running **mobilertc-abdroid-studio** **example**, **example2** and **customuidemo** 

Then,

apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion '26.0.2'

    defaultConfig {
        applicationId "us.zoom.sdkexample"
        minSdkVersion 14
        targetSdkVersion 26
		versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }

    **splits {
        abi {
            enable true
            reset()
            include 'x86', 'armeabi-v7a'
            universalApk true
        }
    }** 
}

dependencies {
    compile 'com.android.support:support-v4:26.1.0'
    compile 'com.android.support:recyclerview-v7:26.1.0'
    compile project(':commonlib')
    compile project(':mobilertc')
}

Then i added the above highlighted code in build.gradle then project compiled successfully but when i run the app i got below exception

us.zoom.sdkexample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: us.zoom.sdkexample, PID: 4875
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/us.zoom.sdkexample-3BrZHYwIk5aYcliAtK_JZg==/base.apk"],nativeLibraryDirectories=[/data/app/us.zoom.sdkexample-3BrZHYwIk5aYcliAtK_JZg==/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libzoom_stlport.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at com.zipow.cmmlib.AppContext.<clinit>(AppContext.java:31)
        at com.zipow.cmmlib.AppContext.initialize(AppContext.java:64)
        at us.zoom.sdk.ZoomSDK.initialize(ZoomSDK.java:243)
        at us.zoom.sdk.ZoomSDK.initialize(ZoomSDK.java:202)
        at us.zoom.sdkexample.WelcomeActivity.onCreate(WelcomeActivity.java:50)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

I have replaced 

Error:            mZoomSDK.initialize(this, APP_KEY, APP_SECRET, WEB_DOMAIN, this);

APP_KEY, APP_SECRET, WEB_DOMAIN in Constants.java file

**Comment by JackyDuu** [comment]
Currently, Zoom sdk only provide libraries for armabi-v7a, You need specify ABIs in your gradle script 
 ndk {
            abiFilters  "armeabi-v7a" // Specifies the ABI configurations of your native
      // libraries Gradle should build and package with your AP
        }

**Comment by kaprat** [comment]
![I am getting this issue when i run both example & example2](https://user-images.githubusercontent.com/29137068/48657574-d9fc1c80-ea58-11e8-985a-fbf00f6ee7ea.png)

**Comment by JackyDuu** [comment]
You should get a vaild app key/secret before integrating zoom sdk, please refer to https://marketplace.zoom.us/docs/guides/zoom-sdks/android
